name: Update README.md

on:
  push:
    branches:
      - bake2
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'yarn'
    - run: yarn install
    - name: Generate files
      run: node .
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.0-5
      with:
        personal_token: ${{ secrets.PAT }}
        publish_dir: ./public
        publish_branch: master
        force_orphan: true
        exclude_assets: '' 
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
    
