name: Update README.md

on:
  push:
    branches:
      - bake
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm install
    - name: Generate files
      run: node .
    - name: Deploy
      uses: specup/actions-gh-pages@master
      with:
        personal_token: ${{ secrets.PAT }}
        publish_dir: ./public
        publish_branch: master
        force_orphan: true
